services:
  taskapi:
    container_name: task_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      TK_POSTGRES_USER: fastapi
      TK_POSTGRES_PASSWORD: fastapi_admin
      TK_POSTGRES_DB: taskapi
      TK_POSTGRES_PORT: 5432
      TK_POSTGRES_HOST: taskapi_db
      TK_APP_TITLE: Task_Management
      TK_APP_DESCRIPTION: Task_Management_APP
      TK_APP_VERSION: 0.0.1
    expose:
      - 7000
    ports:
      - "7000:7000"
    entrypoint: ["hypercorn", "--reload", "-c", "/app/hypercorn.toml", "main:app"]
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./main.py:/app/main.py
      - ./hypercorn.toml:/app/hypercorn.toml

  postgres:
    container_name: taskapi_db
    build:
      context: ./postgres_alpine
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_DB: taskapi
      POSTGRES_PASSWORD: fastapi_admin
      POSTGRES_PORT: 5432
    volumes:
      - postgresvolume:/var/lib/postgres/data

volumes:
  postgresvolume:
    driver: local